---
:verbose: false
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid

:queues:
  - [critical, 2]
  - default
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15
